### ISSUE TITLE
Access token is required now

### ISSUE THREAD

**Issue by SantinoPetrovic** [zomars/bolt-public-instagram#1]
Look in this repo: https://github.com/vinkla/instagram

I believe you need to do some changes because the current extension doesn't work now.

**Comment by zomars** [comment]
Thanks for the heads up. I've just got up to date with the issue. I'll try to figure out a way to update it without causing much trouble. PRs are also welcome! ;)

**Comment by zomars** [comment]
I've dug up a little bit more and came up with a conclusion about access tokens. Even if it is the "right" way to do, it would defeat the purpose of this extension. And that is to access to already public instagram data. With the token approach, you would need to have that specific account credentials to generate it. Which in many cases it can be tedious for some people. 

I'm still open to implement it, but it is not my priority for now. So if you would like to try a PR I would happily merge it.

Cheers mate!
